name: Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  DIST_ARTIFACT_NAME: dist-artifact

jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        run: npm run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_SHEET_ID: ${{ secrets.VITE_GOOGLE_SHEET_ID }}
          VITE_GOOGLE_VALIDATE_SCRIPT_ID: ${{ secrets.VITE_GOOGLE_VALIDATE_SCRIPT_ID }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        if: success()
        with:
          name: ${{ env.DIST_ARTIFACT_NAME }}
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [lint-and-build]
    if: ${{ !cancelled() && github.ref == 'refs/heads/develop' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.DIST_ARTIFACT_NAME }}
          path: pages/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: pages/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
